### ISSUE TITLE
Consider using a fixed code style

### ISSUE THREAD

**Issue by elcorto** [Photon-AI-Research/InSituML#13]
I suggest using [`black`](https://black.readthedocs.io). E.g. I personally use `black -l79`. Once we have a `pyproject.toml` we can set 

```toml
[tool.black]
line-length = 79
```
